var h,aa=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}},ba="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},ca="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,da=function(a,b){if(b){var c=ca;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&
ba(c,a,{configurable:!0,writable:!0,value:b})}},ea=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
da("WeakMap",function(a){function b(){}function c(k){ea(k,e)||ba(k,e,{value:new b})}function d(k){var l=Object[k];l&&(Object[k]=function(m){if(m instanceof b)return m;c(m);return l(m)})}if(function(){if(!a||!Object.seal)return!1;try{var k=Object.seal({}),l=Object.seal({}),m=new a([[k,2],[l,3]]);if(2!=m.get(k)||3!=m.get(l))return!1;m["delete"](k);m.set(l,4);return!m.has(k)&&4==m.get(l)}catch(n){return!1}}())return a;var e="$jscomp_hidden_"+Math.random();d("freeze");d("preventExtensions");d("seal");
var f=0,g=function(k){this.u=(f+=Math.random()+1).toString();if(k){var l="undefined"!=typeof Symbol&&Symbol.iterator&&k[Symbol.iterator];for(k=l?l.call(k):{next:aa(k)};!(l=k.next()).done;)l=l.value,this.set(l[0],l[1])}};g.prototype.set=function(k,l){c(k);if(!ea(k,e))throw Error("WeakMap key fail: "+k);k[e][this.u]=l;return this};g.prototype.get=function(k){return ea(k,e)?k[e][this.u]:void 0};g.prototype.has=function(k){return ea(k,e)&&ea(k[e],this.u)};g.prototype["delete"]=function(k){return ea(k,
e)&&ea(k[e],this.u)?delete k[e][this.u]:!1};return g});
var fa=fa||{},p=this,q=function(a){return void 0!==a},r=function(a){return"string"==typeof a},ha=function(a){return"number"==typeof a},ia=function(a,b,c){a=a.split(".");c=c||p;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&q(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}},ka=function(a,b){a=a.split(".");b=b||p;for(var c=0;c<a.length;c++)if(b=b[a[c]],null==b)return null;return b},la=function(){},t=function(a){var b=typeof a;
if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b},u=function(a){return"array"==t(a)},ma=function(a){var b=t(a);return"array"==b||"object"==b&&"number"==typeof a.length},v=function(a){return"function"==t(a)},w=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},pa=function(a){return a[na]||(a[na]=++oa)},na="closure_uid_"+(1E9*Math.random()>>>0),oa=0,qa=function(a,b,c){return a.call.apply(a.bind,arguments)},ra=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=
Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}},x=function(a,b,c){x=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?qa:ra;return x.apply(null,arguments)},sa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}},ta=
Date.now||function(){return+new Date},y=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.Ld=function(d,e,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[e].apply(d,g)}};var z=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,z);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};y(z,Error);z.prototype.name="CustomError";var ua;var va=function(a,b){a=a.split("%s");for(var c="",d=a.length-1,e=0;e<d;e++)c+=a[e]+(e<b.length?b[e]:"%s");z.call(this,c+a[d])};y(va,z);va.prototype.name="AssertionError";
var wa=function(a,b,c,d){var e="Assertion failed";if(c){e+=": "+c;var f=d}else a&&(e+=": "+a,f=b);throw new va(""+e,f||[]);},A=function(a,b,c){a||wa("",null,b,Array.prototype.slice.call(arguments,2));return a},B=function(a,b){throw new va("Failure"+(a?": "+a:""),Array.prototype.slice.call(arguments,1));},xa=function(a,b,c){ha(a)||wa("Expected number but got %s: %s.",[t(a),a],b,Array.prototype.slice.call(arguments,2));return a},ya=function(a,b,c){v(a)||wa("Expected function but got %s: %s.",[t(a),
a],b,Array.prototype.slice.call(arguments,2))};var za=Array.prototype.indexOf?function(a,b){A(null!=a.length);return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(r(a))return r(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},Aa=Array.prototype.forEach?function(a,b,c){A(null!=a.length);Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=r(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Ba=Array.prototype.map?function(a,b){A(null!=a.length);return Array.prototype.map.call(a,
b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=r(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d},Ca=Array.prototype.some?function(a,b){A(null!=a.length);return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1},Ea=function(a){a:{var b=Da;for(var c=a.length,d=r(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?
null:r(a)?a.charAt(b):a[b]},Fa=function(a,b){b=za(a,b);var c;if(c=0<=b)A(null!=a.length),Array.prototype.splice.call(a,b,1);return c},Ga=function(a){return Array.prototype.concat.apply([],arguments)},Ia=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]},Ka=function(a,b){a.sort(b||Ja)},Ja=function(a,b){return a>b?1:a<b?-1:0};var La=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)},Ma=function(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1},Na=function(a){var b=[],c=0,d;for(d in a)b[c++]=a[d];return b},Oa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" "),Pa=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Oa.length;f++)c=Oa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Qa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]},Ya=function(a){if(!Ra.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Sa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ta,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ua,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Va,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Wa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Xa,"&#0;"));return a},Sa=/&/g,Ta=/</g,Ua=/>/g,Va=/"/g,Wa=/'/g,Xa=/\x00/g,Ra=
/[\x00&<>"']/,Za=function(a,b){return a<b?-1:a>b?1:0};var $a={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},ab={"'":"\\'"},bb=function(a){a=String(a);for(var b=['"'],c=0;c<a.length;c++){var d=a.charAt(c),e=d.charCodeAt(0),f=c+1,g;if(!(g=$a[d])){if(!(31<e&&127>e))if(d in ab)d=ab[d];else if(d in $a)d=ab[d]=$a[d];else{g=d.charCodeAt(0);if(31<g&&127>g)e=d;else{if(256>g){if(e="\\x",16>g||256<g)e+="0"}else e="\\u",4096>g&&(e+="0");e+=g.toString(16).toUpperCase()}d=ab[d]=e}g=d}b[f]=g}b.push('"');
return b.join("")},cb=function(a){isFinite(a)&&(a=String(a));return r(a)?/^\s*-?0x/i.test(a)?parseInt(a,16):parseInt(a,10):NaN};var db=function(a,b){this.$b=a.name||null;this.Ac=a.Md;this.Z={};for(a=0;a<b.length;a++){var c=b[a];this.Z[c.W]=c}};db.prototype.getName=function(){return this.$b};db.prototype.wa=function(){return this.Ac?this.Ac.A():null};var eb=function(a){a=Na(a.Z);Ka(a,function(b,c){return b.W-c.W});return a};var fb=function(a,b,c){this.v=a;A(!/[^0-9]/.test(b));this.W=b;this.$b=c.name;this.Xb=!!c.Pd;this.da=c.Rb;this.ac=c.type};fb.prototype.wa=function(){return this.v.prototype.A()};fb.prototype.getName=function(){return this.$b};var gb=function(){this.J={};this.Z=this.A().Z;this.K=this.Pc=null},hb=function(a,b,c){c=c||a;for(var d in a.J){var e=Number(d);a.Z[e]||b.call(c,e,a.J[d])}};h=gb.prototype;h.has=function(a){A(a.wa()==this.A(),"The current message does not contain the given field");return null!=this.J[a.W]};
h.get=function(a,b){A(a.wa()==this.A(),"The current message does not contain the given field");var c=a.W;a=ib(this,c);this.Z[c].Xb?(b=b||0,A(0<=b&&b<a.length,"Given index %s is out of bounds.  Repeated field length: %s",b,a.length),b=a[b]):b=a;return b};h.set=function(a,b){A(a.wa()==this.A(),"The current message does not contain the given field");C(this,a.W,b)};h.add=function(a,b){A(a.wa()==this.A(),"The current message does not contain the given field");jb(this,a.W,b)};
h.clear=function(a){A(a.wa()==this.A(),"The current message does not contain the given field");a=a.W;delete this.J[a];this.K&&delete this.K[a]};
var kb=function(a,b){A(a.constructor==b.constructor,"The source message must have the same type.");for(var c=eb(a.A()),d=0;d<c.length;d++){var e=c[d],f=e.W;if(null!=b.J[f]){a.K&&delete a.K[e.W];var g=11==e.da||10==e.da;if(e.Xb){e=ib(b,f)||[];for(var k=0;k<e.length;k++)jb(a,f,g?e[k].clone():e[k])}else e=ib(b,f),g?(g=ib(a,f))?kb(g,e):C(a,f,e.clone()):C(a,f,e)}}};
gb.prototype.clone=function(){var a=new this.constructor;A(a.constructor==this.constructor,"The source message must have the same type.");a!=this&&(a.J={},a.K&&(a.K={}),kb(a,this));return a};
var ib=function(a,b){var c=a.J[b];return null==c?null:a.Pc?b in a.K?a.K[b]:(c=a.Pc.Nd(a,a.Z[b],c),a.K[b]=c):c},C=function(a,b,c){var d=a.Z[b];14==d.da?xa(c):A(Object(c).constructor==d.ac);a.J[b]=c;a.K&&(a.K[b]=c)},jb=function(a,b,c){var d=a.Z[b];14==d.da?xa(c):A(Object(c).constructor==d.ac);a.J[b]||(a.J[b]=[]);a.J[b].push(c);a.K&&delete a.K[b]},lb=function(a,b){var c=[],d=b[0],e;for(e in b)0!=e&&c.push(new fb(a,e,b[e]));return new db(d,c)};var D=function(){gb.call(this)};y(D,gb);var mb=null,nb=function(){gb.call(this)};y(nb,gb);var ob=null;D.prototype.A=function(){var a=mb;a||(mb=a=lb(D,{0:{name:"Version",sd:"buzz.channel.Version"},1:{name:"major_version",Rb:5,type:Number},2:{name:"minor_version",Rb:5,type:Number}}));return a};D.A=D.prototype.A;nb.prototype.A=function(){var a=ob;a||(ob=a=lb(nb,{0:{name:"ProtocolVersion",sd:"buzz.channel.ProtocolVersion"},1:{name:"version",Rb:11,type:D}}));return a};nb.A=nb.prototype.A;/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var pb="StopIteration"in p?p.StopIteration:{message:"StopIteration",stack:""},qb=function(){};qb.prototype.next=function(){throw pb;};qb.prototype.Jb=function(){return this};var rb=function(a,b){this.o={};this.g=[];this.hb=this.j=0;var c=arguments.length;if(1<c){if(c%2)throw Error("Uneven number of arguments");for(var d=0;d<c;d+=2)this.set(arguments[d],arguments[d+1])}else a&&this.addAll(a)};h=rb.prototype;h.O=function(){sb(this);for(var a=[],b=0;b<this.g.length;b++)a.push(this.o[this.g[b]]);return a};h.ea=function(){sb(this);return this.g.concat()};h.Ha=function(a){return tb(this.o,a)};h.clear=function(){this.o={};this.hb=this.j=this.g.length=0};
h.remove=function(a){return tb(this.o,a)?(delete this.o[a],this.j--,this.hb++,this.g.length>2*this.j&&sb(this),!0):!1};var sb=function(a){if(a.j!=a.g.length){for(var b=0,c=0;b<a.g.length;){var d=a.g[b];tb(a.o,d)&&(a.g[c++]=d);b++}a.g.length=c}if(a.j!=a.g.length){var e={};for(c=b=0;b<a.g.length;)d=a.g[b],tb(e,d)||(a.g[c++]=d,e[d]=1),b++;a.g.length=c}};h=rb.prototype;h.get=function(a,b){return tb(this.o,a)?this.o[a]:b};
h.set=function(a,b){tb(this.o,a)||(this.j++,this.g.push(a),this.hb++);this.o[a]=b};h.addAll=function(a){if(a instanceof rb)for(var b=a.ea(),c=0;c<b.length;c++)this.set(b[c],a.get(b[c]));else for(b in a)this.set(b,a[b])};h.forEach=function(a,b){for(var c=this.ea(),d=0;d<c.length;d++){var e=c[d],f=this.get(e);a.call(b,f,e,this)}};h.clone=function(){return new rb(this)};
h.Jb=function(a){sb(this);var b=0,c=this.hb,d=this,e=new qb;e.next=function(){if(c!=d.hb)throw Error("The map has changed since the iterator was created");if(b>=d.g.length)throw pb;var f=d.g[b++];return a?f:d.o[f]};return e};var tb=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};var ub=function(a){if(a.O&&"function"==typeof a.O)return a.O();if(r(a))return a.split("");if(ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return Na(a)},vb=function(a,b,c){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,c);else if(ma(a)||r(a))Aa(a,b,c);else{if(a.ea&&"function"==typeof a.ea)var d=a.ea();else if(a.O&&"function"==typeof a.O)d=void 0;else if(ma(a)||r(a)){d=[];for(var e=a.length,f=0;f<e;f++)d.push(f)}else for(f in d=[],e=0,a)d[e++]=f;e=ub(a);f=e.length;for(var g=
0;g<f;g++)b.call(c,e[g],d&&d[g],a)}};var wb=function(a){this.o=new rb;a&&this.addAll(a)},xb=function(a){var b=typeof a;return"object"==b&&a||"function"==b?"o"+pa(a):b.substr(0,1)+a};h=wb.prototype;h.add=function(a){this.o.set(xb(a),a)};h.addAll=function(a){a=ub(a);for(var b=a.length,c=0;c<b;c++)this.add(a[c])};h.ab=function(a){a=ub(a);for(var b=a.length,c=0;c<b;c++)this.remove(a[c])};h.remove=function(a){return this.o.remove(xb(a))};h.clear=function(){this.o.clear()};h.contains=function(a){return this.o.Ha(xb(a))};h.O=function(){return this.o.O()};
h.clone=function(){return new wb(this)};h.Jb=function(){return this.o.Jb(!1)};new wb([1,2,3]);new wb([1,2]);var E;a:{var yb=p.navigator;if(yb){var zb=yb.userAgent;if(zb){E=zb;break a}}E=""}var F=function(a){return-1!=E.indexOf(a)};var Ab=function(a){Ab[" "](a);return a};Ab[" "]=la;var Bb=function(a,b){try{return Ab(a[b]),!0}catch(c){}return!1},Db=function(a,b){var c=Cb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Eb=F("Opera"),G=F("Trident")||F("MSIE"),Fb=F("Edge"),Gb=F("Gecko")&&!(-1!=E.toLowerCase().indexOf("webkit")&&!F("Edge"))&&!(F("Trident")||F("MSIE"))&&!F("Edge"),Hb=-1!=E.toLowerCase().indexOf("webkit")&&!F("Edge"),Ib=F("Macintosh"),Jb=F("Windows"),Kb=F("Android"),Lb=F("iPhone")&&!F("iPod")&&!F("iPad"),Mb=F("iPad"),Nb=F("iPod"),Ob=function(){var a=p.document;return a?a.documentMode:void 0},Pb;
a:{var Qb="",Rb=function(){var a=E;if(Gb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Fb)return/Edge\/([\d\.]+)/.exec(a);if(G)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Hb)return/WebKit\/(\S+)/.exec(a);if(Eb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Rb&&(Qb=Rb?Rb[1]:"");if(G){var Sb=Ob();if(null!=Sb&&Sb>parseFloat(Qb)){Pb=String(Sb);break a}}Pb=Qb}
var Tb=Pb,Cb={},Ub=function(a){return Db(a,function(){for(var b=0,c=Qa(String(Tb)).split("."),d=Qa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",k=d[f]||"";do{g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==g[0].length&&0==k[0].length)break;b=Za(0==g[1].length?0:parseInt(g[1],10),0==k[1].length?0:parseInt(k[1],10))||Za(0==g[2].length,0==k[2].length)||Za(g[2],k[2]);g=g[3];k=k[3]}while(0==b)}return 0<=b})},Vb;var Wb=p.document;
Vb=Wb&&G?Ob()||("CSS1Compat"==Wb.compatMode?parseInt(Tb,10):5):void 0;var Xb=Object.freeze||function(a){return a};var Yb=function(){this.name="FINEST";this.value=300};Yb.prototype.toString=function(){return this.name};var Zb=new Yb;var $b=function(){this.Xc=ta()},ac=null;$b.prototype.set=function(a){this.Xc=a};$b.prototype.reset=function(){this.set(ta())};$b.prototype.get=function(){return this.Xc};var bc={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};var ec=function(a,b){this.oc=a===cc&&b||"";this.fd=dc};ec.prototype.ga=!0;ec.prototype.T=function(){return this.oc};ec.prototype.toString=function(){return"Const{"+this.oc+"}"};var fc=function(a){if(a instanceof ec&&a.constructor===ec&&a.fd===dc)return a.oc;B("expected object of type Const, got '"+a+"'");return"type_error:Const"},dc={},cc={};var gc=function(){this.fc=""};gc.prototype.ga=!0;gc.prototype.T=function(){return this.fc.toString()};gc.prototype.toString=function(){return"SafeScript{"+this.fc+"}"};gc.prototype.oa=function(a){this.fc=a;return this};(new gc).oa("");var ic=function(){this.hc="";this.gd=hc};h=ic.prototype;h.ga=!0;h.T=function(){return this.hc.toString()};h.Tb=!0;h.Sa=function(){return 1};h.toString=function(){return"TrustedResourceUrl{"+this.hc+"}"};var hc={};var kc=function(){this.wb="";this.ed=jc};h=kc.prototype;h.ga=!0;h.T=function(){return this.wb.toString()};h.Tb=!0;h.Sa=function(){return 1};h.toString=function(){return"SafeUrl{"+this.wb+"}"};
var lc=function(a){if(a instanceof kc&&a.constructor===kc&&a.ed===jc)return a.wb;B("expected object of type SafeUrl, got '"+a+"' of type "+t(a));return"type_error:SafeUrl"},mc=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i,oc=function(a){if(a instanceof kc)return a;a="object"==typeof a&&a.ga?a.T():String(a);mc.test(a)||(a="about:invalid#zClosurez");return nc(a)},jc={},nc=function(a){var b=new kc;b.wb=a;return b};nc("about:blank");var H=function(){this.vb="";this.dd=pc};H.prototype.ga=!0;var pc={};H.prototype.T=function(){return this.vb};H.prototype.toString=function(){return"SafeStyle{"+this.vb+"}"};H.prototype.oa=function(a){this.vb=a;return this};
var qc=(new H).oa(""),sc=function(a){if(a instanceof kc)return'url("'+lc(a).toString().replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';a=a instanceof ec?fc(a):rc(String(a));if(/[{;}]/.test(a))throw new va("Value does not allow [{;}], got: %s.",[a]);return a},rc=function(a){var b=a.replace(tc,"$1").replace(tc,"$1").replace(uc,"url");if(vc.test(b)){if(wc.test(a))return B("String value disallows comments, got: "+a),"zClosurez";for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==
e&&b&&(c=!c)}if(!b||!c)return B("String value requires balanced quotes, got: "+a),"zClosurez";if(!xc(a))return B("String value requires balanced square brackets and one identifier per pair of brackets, got: "+a),"zClosurez"}else return B("String value allows only [-,.\"'%_!# a-zA-Z0-9\\[\\]] and simple functions, got: "+a),"zClosurez";return yc(a)},xc=function(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&
!c.test(e))return!1}return b},vc=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/,uc=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,tc=/\b(hsl|hsla|rgb|rgba|matrix|calc|minmax|fit-content|repeat|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g,wc=/\/\*/,yc=function(a){return a.replace(uc,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(g,k,l){f=k;return l});b=oc(d).T();return c+f+b+f+e})};var zc=function(){this.gc=""};zc.prototype.ga=!0;zc.prototype.T=function(){return this.gc};zc.prototype.toString=function(){return"SafeStyleSheet{"+this.gc+"}"};zc.prototype.oa=function(a){this.gc=a;return this};(new zc).oa("");var Cc=function(){this.ub="";this.cd=Bc;this.Fc=null};h=Cc.prototype;h.Tb=!0;h.Sa=function(){return this.Fc};h.ga=!0;h.T=function(){return this.ub.toString()};h.toString=function(){return"SafeHtml{"+this.ub+"}"};
var Dc=function(a){if(a instanceof Cc&&a.constructor===Cc&&a.cd===Bc)return a.ub;B("expected object of type SafeHtml, got '"+a+"' of type "+t(a));return"type_error:SafeHtml"},Ec=/^[a-zA-Z0-9-]+$/,Fc={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},Hc=function(a){var b=0,c="",d=function(e){if(u(e))Aa(e,d);else{if(!(e instanceof Cc)){var f="object"==typeof e,g=null;f&&e.Tb&&(g=e.Sa());e=Gc(Ya(f&&e.ga?e.T():String(e)),g)}c+=Dc(e).toString();e=e.Sa();0==b?b=e:0!=e&&b!=e&&
(b=null)}};Aa(arguments,d);return Gc(c,b)},Bc={},Gc=function(a,b){return(new Cc).oa(a,b)};Cc.prototype.oa=function(a,b){this.ub=a;this.Fc=b;return this};Gc("<!DOCTYPE html>",0);var Ic=Gc("",0);Gc("<br>",0);var Jc=function(){ac||(ac=new $b)},Kc=function(){ac||(ac=new $b)};y(Kc,Jc);var I=function(){this.la=this.la;this.za=this.za};I.prototype.la=!1;I.prototype.Nb=function(){this.la||(this.la=!0,this.f())};var Lc=function(a,b){a.la?q(void 0)?b.call(void 0):b():(a.za||(a.za=[]),a.za.push(q(void 0)?x(b,void 0):b))};I.prototype.f=function(){if(this.za)for(;this.za.length;)this.za.shift()()};var J=function(a){a&&"function"==typeof a.Nb&&a.Nb()};var Mc=function(a,b){this.type=a;this.currentTarget=this.target=b;this.defaultPrevented=this.Ca=!1;this.$c=!0};Mc.prototype.stopPropagation=function(){this.Ca=!0};Mc.prototype.preventDefault=function(){this.defaultPrevented=!0;this.$c=!1};var Nc;(Nc=!G)||(Nc=9<=Number(Vb));var Oc=Nc,Pc=G&&!Ub("9"),Qc=function(){if(!p.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{p.addEventListener("test",la,b),p.removeEventListener("test",la,b)}catch(c){}return a}();var Rc=function(a,b){Mc.call(this,a?a.type:"");this.relatedTarget=this.currentTarget=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.offsetY=this.offsetX=0;this.key="";this.charCode=this.keyCode=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.state=null;this.pointerId=0;this.pointerType="";this.ma=null;a&&this.Vb(a,b)};y(Rc,Mc);var Sc=Xb({2:"touch",3:"pen",4:"mouse"});
Rc.prototype.Vb=function(a,b){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.currentTarget=b;(b=a.relatedTarget)?Gb&&(Bb(b,"nodeName")||(b=null)):"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.offsetX=Hb||void 0!==a.offsetX?
a.offsetX:a.layerX,this.offsetY=Hb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||0,this.screenY=a.screenY||0);this.button=a.button;this.keyCode=a.keyCode||0;this.key=a.key||"";this.charCode=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.pointerId=a.pointerId||0;this.pointerType=r(a.pointerType)?
a.pointerType:Sc[a.pointerType]||"";this.state=a.state;this.ma=a;a.defaultPrevented&&this.preventDefault()};Rc.prototype.stopPropagation=function(){Rc.H.stopPropagation.call(this);this.ma.stopPropagation?this.ma.stopPropagation():this.ma.cancelBubble=!0};Rc.prototype.preventDefault=function(){Rc.H.preventDefault.call(this);var a=this.ma;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Pc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Tc="closure_listenable_"+(1E6*Math.random()|0),Uc=function(a){return!(!a||!a[Tc])},Vc=0;var Wc=function(a,b,c,d,e){this.listener=a;this.xb=null;this.src=b;this.type=c;this.capture=!!d;this.xa=e;this.key=++Vc;this.Pa=this.lb=!1},Xc=function(a){a.Pa=!0;a.listener=null;a.xb=null;a.src=null;a.xa=null};var Yc=function(a){this.src=a;this.B={};this.gb=0};Yc.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.B[f];a||(a=this.B[f]=[],this.gb++);var g=Zc(a,b,d,e);-1<g?(b=a[g],c||(b.lb=!1)):(b=new Wc(b,this.src,f,!!d,e),b.lb=c,a.push(b));return b};Yc.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.B))return!1;var e=this.B[a];b=Zc(e,b,c,d);return-1<b?(Xc(e[b]),A(null!=e.length),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.B[a],this.gb--),!0):!1};
var $c=function(a,b){var c=b.type;c in a.B&&Fa(a.B[c],b)&&(Xc(b),0==a.B[c].length&&(delete a.B[c],a.gb--))};Yc.prototype.ab=function(a){a=a&&a.toString();var b=0,c;for(c in this.B)if(!a||c==a){for(var d=this.B[c],e=0;e<d.length;e++)++b,Xc(d[e]);delete this.B[c];this.gb--}};Yc.prototype.Ta=function(a,b,c,d){a=this.B[a.toString()];var e=-1;a&&(e=Zc(a,b,c,d));return-1<e?a[e]:null};
Yc.prototype.hasListener=function(a,b){var c=q(a),d=c?a.toString():"",e=q(b);return Ma(this.B,function(f){for(var g=0;g<f.length;++g)if(!(c&&f[g].type!=d||e&&f[g].capture!=b))return!0;return!1})};var Zc=function(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.Pa&&f.listener==b&&f.capture==!!c&&f.xa==d)return e}return-1};var ad="closure_lm_"+(1E6*Math.random()|0),bd={},cd=0,ed=function(a,b,c,d,e){if(d&&d.once)return dd(a,b,c,d,e);if(u(b)){for(var f=0;f<b.length;f++)ed(a,b[f],c,d,e);return null}c=fd(c);return Uc(a)?a.Xa(b,c,w(d)?!!d.capture:!!d,e):gd(a,b,c,!1,d,e)},gd=function(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var g=w(e)?!!e.capture:!!e,k=hd(a);k||(a[ad]=k=new Yc(a));c=k.add(b,c,d,g,f);if(c.xb)return c;d=id();c.xb=d;d.src=a;d.listener=c;if(a.addEventListener)Qc||(e=g),void 0===e&&(e=!1),a.addEventListener(b.toString(),
d,e);else if(a.attachEvent)a.attachEvent(jd(b.toString()),d);else if(a.addListener&&a.removeListener)A("change"===b,"MediaQueryList only has a change event"),a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");cd++;return c},id=function(){var a=kd,b=Oc?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b},dd=function(a,b,c,d,e){if(u(b)){for(var f=0;f<b.length;f++)dd(a,b[f],c,d,e);return null}c=fd(c);return Uc(a)?
a.Yb(b,c,w(d)?!!d.capture:!!d,e):gd(a,b,c,!0,d,e)},ld=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)ld(a,b[f],c,d,e);else d=w(d)?!!d.capture:!!d,c=fd(c),Uc(a)?a.pc(b,c,d,e):a&&(a=hd(a))&&(b=a.Ta(b,c,d,e))&&md(b)},md=function(a){if(!ha(a)&&a&&!a.Pa){var b=a.src;if(Uc(b))$c(b.S,a);else{var c=a.type,d=a.xb;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(jd(c),d):b.addListener&&b.removeListener&&b.removeListener(d);cd--;(c=hd(b))?($c(c,a),0==c.gb&&(c.src=
null,b[ad]=null)):Xc(a)}}},nd=function(a,b,c,d,e){c=fd(c);d=!!d;return Uc(a)?a.Ta(b,c,d,e):a?(a=hd(a))?a.Ta(b,c,d,e):null:null},jd=function(a){return a in bd?bd[a]:bd[a]="on"+a},pd=function(a,b,c,d){var e=!0;if(a=hd(a))if(b=a.B[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.Pa&&(f=od(f,d),e=e&&!1!==f)}return e},od=function(a,b){var c=a.listener,d=a.xa||a.src;a.lb&&md(a);return c.call(d,b)},kd=function(a,b){if(a.Pa)return!0;if(!Oc){var c=b||ka("window.event");b=new Rc(c,
this);var d=!0;if(!(0>c.keyCode||void 0!=c.returnValue)){a:{var e=!1;if(0==c.keyCode)try{c.keyCode=-1;break a}catch(g){e=!0}if(e||void 0==c.returnValue)c.returnValue=!0}c=[];for(e=b.currentTarget;e;e=e.parentNode)c.push(e);a=a.type;for(e=c.length-1;!b.Ca&&0<=e;e--){b.currentTarget=c[e];var f=pd(c[e],a,!0,b);d=d&&f}for(e=0;!b.Ca&&e<c.length;e++)b.currentTarget=c[e],f=pd(c[e],a,!1,b),d=d&&f}return d}return od(a,new Rc(b,this))},hd=function(a){a=a[ad];return a instanceof Yc?a:null},qd="__closure_events_fn_"+
(1E9*Math.random()>>>0),fd=function(a){A(a,"Listener can not be null.");if(v(a))return a;A(a.handleEvent,"An object listener must have handleEvent method.");a[qd]||(a[qd]=function(b){return a.handleEvent(b)});return a[qd]};var K=function(){I.call(this);this.S=new Yc(this);this.hd=this;this.dc=null};y(K,I);K.prototype[Tc]=!0;h=K.prototype;h.addEventListener=function(a,b,c,d){ed(this,a,b,c,d)};h.removeEventListener=function(a,b,c,d){ld(this,a,b,c,d)};
h.dispatchEvent=function(a){rd(this);var b=this.dc;if(b){var c=[];for(var d=1;b;b=b.dc)c.push(b),A(1E3>++d,"infinite loop")}b=this.hd;d=a.type||a;if(r(a))a=new Mc(a,b);else if(a instanceof Mc)a.target=a.target||b;else{var e=a;a=new Mc(d,b);Pa(a,e)}e=!0;if(c)for(var f=c.length-1;!a.Ca&&0<=f;f--){var g=a.currentTarget=c[f];e=sd(g,d,!0,a)&&e}a.Ca||(g=a.currentTarget=b,e=sd(g,d,!0,a)&&e,a.Ca||(e=sd(g,d,!1,a)&&e));if(c)for(f=0;!a.Ca&&f<c.length;f++)g=a.currentTarget=c[f],e=sd(g,d,!1,a)&&e;return e};
h.f=function(){K.H.f.call(this);this.S&&this.S.ab(void 0);this.dc=null};h.Xa=function(a,b,c,d){rd(this);return this.S.add(String(a),b,!1,c,d)};h.Yb=function(a,b,c,d){return this.S.add(String(a),b,!0,c,d)};h.pc=function(a,b,c,d){this.S.remove(String(a),b,c,d)};var sd=function(a,b,c,d){b=a.S.B[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var g=b[f];if(g&&!g.Pa&&g.capture==c){var k=g.listener,l=g.xa||g.src;g.lb&&$c(a.S,g);e=!1!==k.call(l,d)&&e}}return e&&0!=d.$c};
K.prototype.Ta=function(a,b,c,d){return this.S.Ta(String(a),b,c,d)};K.prototype.hasListener=function(a,b){return this.S.hasListener(q(a)?String(a):void 0,b)};var rd=function(a){A(a.S,"Event target is not initialized. Did you call the superclass (goog.events.EventTarget) constructor?")};var td=function(){this.yb=void 0};td.prototype.Bb=function(a){var b=[];ud(this,a,b);return b.join("")};
var ud=function(a,b,c){if(null==b)c.push("null");else{if("object"==typeof b){if(u(b)){var d=b;b=d.length;c.push("[");for(var e="",f=0;f<b;f++)c.push(e),e=d[f],ud(a,a.yb?a.yb.call(d,String(f),e):e,c),e=",";c.push("]");return}if(b instanceof String||b instanceof Number||b instanceof Boolean)b=b.valueOf();else{c.push("{");f="";for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&(e=b[d],"function"!=typeof e&&(c.push(f),vd(d,c),c.push(":"),ud(a,a.yb?a.yb.call(b,d,e):e,c),f=","));c.push("}");return}}switch(typeof b){case "string":vd(b,
c);break;case "number":c.push(isFinite(b)&&!isNaN(b)?String(b):"null");break;case "boolean":c.push(String(b));break;case "function":c.push("null");break;default:throw Error("Unknown type: "+typeof b);}}},wd={'"':'\\"',"\\":"\\\\","/":"\\/","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\u000b"},xd=/\uffff/.test("\uffff")?/[\\"\x00-\x1f\x7f-\uffff]/g:/[\\"\x00-\x1f\x7f-\xff]/g,vd=function(a,b){b.push('"',a.replace(xd,function(c){var d=wd[c];d||(d="\\u"+(c.charCodeAt(0)|65536).toString(16).substr(1),
wd[c]=d);return d}),'"')};var yd=function(a){var b=L.c;b&&b.log(Zb,a,void 0)},M=function(a,b){a&&a.Qd(b,void 0)},N=function(a){var b=L.c;b&&b.info(a,void 0)},O=function(a,b){a&&a.Od(b,void 0)};var zd=function(a,b){this.xd=100;this.nd=a;this.Dd=b;this.sb=0;this.pb=null};zd.prototype.get=function(){if(0<this.sb){this.sb--;var a=this.pb;this.pb=a.next;a.next=null}else a=this.nd();return a};zd.prototype.put=function(a){this.Dd(a);this.sb<this.xd&&(this.sb++,a.next=this.pb,this.pb=a)};var Ad=function(a){p.setTimeout(function(){throw a;},0)},Bd,Cd=function(){var a=p.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!F("Presto")&&(a=function(){var e=document.createElement("IFRAME");e.style.display="none";e.src="";document.documentElement.appendChild(e);var f=e.contentWindow;e=f.document;e.open();e.write("");e.close();var g="callImmediate"+Math.random(),k="file:"==f.location.protocol?"*":f.location.protocol+"//"+f.location.host;
e=x(function(l){if(("*"==k||l.origin==k)&&l.data==g)this.port1.onmessage()},this);f.addEventListener("message",e,!1);this.port1={};this.port2={postMessage:function(){f.postMessage(g,k)}}});if("undefined"!==typeof a&&!F("Trident")&&!F("MSIE")){var b=new a,c={},d=c;b.port1.onmessage=function(){if(q(c.next)){c=c.next;var e=c.zc;c.zc=null;e()}};return function(e){d.next={zc:e};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof document&&"onreadystatechange"in document.createElement("SCRIPT")?
function(e){var f=document.createElement("SCRIPT");f.onreadystatechange=function(){f.onreadystatechange=null;f.parentNode.removeChild(f);f=null;e();e=null};document.documentElement.appendChild(f)}:function(e){p.setTimeout(e,0)}};var Dd=function(){this.Gb=this.Ea=null},Fd=new zd(function(){return new Ed},function(a){a.reset()});Dd.prototype.add=function(a,b){var c=Fd.get();c.set(a,b);this.Gb?this.Gb.next=c:(A(!this.Ea),this.Ea=c);this.Gb=c};Dd.prototype.remove=function(){var a=null;this.Ea&&(a=this.Ea,this.Ea=this.Ea.next,this.Ea||(this.Gb=null),a.next=null);return a};var Ed=function(){this.next=this.scope=this.Sb=null};Ed.prototype.set=function(a,b){this.Sb=a;this.scope=b;this.next=null};
Ed.prototype.reset=function(){this.next=this.scope=this.Sb=null};var Kd=function(a,b){Gd||Hd();Id||(Gd(),Id=!0);Jd.add(a,b)},Gd,Hd=function(){if(p.Promise&&p.Promise.resolve){var a=p.Promise.resolve(void 0);Gd=function(){a.then(Ld)}}else Gd=function(){var b=Ld;!v(p.setImmediate)||p.Window&&p.Window.prototype&&!F("Edge")&&p.Window.prototype.setImmediate==p.setImmediate?(Bd||(Bd=Cd()),Bd(b)):p.setImmediate(b)}},Id=!1,Jd=new Dd,Ld=function(){for(var a;a=Jd.remove();){try{a.Sb.call(a.scope)}catch(b){Ad(b)}Fd.put(a)}Id=!1};var Md=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var P=function(a){this.l=0;this.ha=void 0;this.Ga=this.ba=this.v=null;this.ob=this.Qb=!1;if(a!=la)try{var b=this;a.call(void 0,function(c){Nd(b,2,c)},function(c){if(!(c instanceof Od))try{if(c instanceof Error)throw c;throw Error("Promise rejected.");}catch(d){}Nd(b,3,c)})}catch(c){Nd(this,3,c)}},Pd=function(){this.next=this.context=this.Na=this.Aa=this.ta=null;this.ib=!1};Pd.prototype.reset=function(){this.context=this.Na=this.Aa=this.ta=null;this.ib=!1};
var Qd=new zd(function(){return new Pd},function(a){a.reset()}),Rd=function(a,b,c){var d=Qd.get();d.Aa=a;d.Na=b;d.context=c;return d};P.prototype.then=function(a,b,c){null!=a&&ya(a,"opt_onFulfilled should be a function.");null!=b&&ya(b,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");return Sd(this,v(a)?a:null,v(b)?b:null,c)};P.prototype.$goog_Thenable=!0;
P.prototype.cancel=function(a){0==this.l&&Kd(function(){var b=new Od(a);Td(this,b)},this)};
var Td=function(a,b){if(0==a.l)if(a.v){var c=a.v;if(c.ba){for(var d=0,e=null,f=null,g=c.ba;g&&(g.ib||(d++,g.ta==a&&(e=g),!(e&&1<d)));g=g.next)e||(f=g);e&&(0==c.l&&1==d?Td(c,b):(f?(d=f,A(c.ba),A(null!=d),d.next==c.Ga&&(c.Ga=d),d.next=d.next.next):Ud(c),Vd(c,e,3,b)))}a.v=null}else Nd(a,3,b)},Xd=function(a,b){a.ba||2!=a.l&&3!=a.l||Wd(a);A(null!=b.Aa);a.Ga?a.Ga.next=b:a.ba=b;a.Ga=b},Sd=function(a,b,c,d){var e=Rd(null,null,null);e.ta=new P(function(f,g){e.Aa=b?function(k){try{var l=b.call(d,k);f(l)}catch(m){g(m)}}:
f;e.Na=c?function(k){try{var l=c.call(d,k);!q(l)&&k instanceof Od?g(k):f(l)}catch(m){g(m)}}:g});e.ta.v=a;Xd(a,e);return e.ta};P.prototype.Id=function(a){A(1==this.l);this.l=0;Nd(this,2,a)};P.prototype.Jd=function(a){A(1==this.l);this.l=0;Nd(this,3,a)};
var Nd=function(a,b,c){if(0==a.l){a===c&&(b=3,c=new TypeError("Promise cannot resolve to itself"));a.l=1;a:{var d=c,e=a.Id,f=a.Jd;if(d instanceof P){null!=e&&ya(e,"opt_onFulfilled should be a function.");null!=f&&ya(f,"opt_onRejected should be a function. Did you pass opt_context as the second argument instead of the third?");Xd(d,Rd(e||la,f||null,a));var g=!0}else if(Md(d))d.then(e,f,a),g=!0;else{if(w(d))try{var k=d.then;if(v(k)){Yd(d,k,e,f,a);g=!0;break a}}catch(l){f.call(a,l);g=!0;break a}g=!1}}g||
(a.ha=c,a.l=b,a.v=null,Wd(a),3!=b||c instanceof Od||Zd(a,c))}},Yd=function(a,b,c,d,e){var f=!1,g=function(l){f||(f=!0,c.call(e,l))},k=function(l){f||(f=!0,d.call(e,l))};try{b.call(a,g,k)}catch(l){k(l)}},Wd=function(a){a.Qb||(a.Qb=!0,Kd(a.rd,a))},Ud=function(a){var b=null;a.ba&&(b=a.ba,a.ba=b.next,b.next=null);a.ba||(a.Ga=null);null!=b&&A(null!=b.Aa);return b};P.prototype.rd=function(){for(var a;a=Ud(this);)Vd(this,a,this.l,this.ha);this.Qb=!1};
var Vd=function(a,b,c,d){if(3==c&&b.Na&&!b.ib)for(;a&&a.ob;a=a.v)a.ob=!1;if(b.ta)b.ta.v=null,$d(b,c,d);else try{b.ib?b.Aa.call(b.context):$d(b,c,d)}catch(e){ae.call(null,e)}Qd.put(b)},$d=function(a,b,c){2==b?a.Aa.call(a.context,c):a.Na&&a.Na.call(a.context,c)},Zd=function(a,b){a.ob=!0;Kd(function(){a.ob&&ae.call(null,b)})},ae=Ad,Od=function(a){z.call(this,a)};y(Od,z);Od.prototype.name="cancel";var be=function(a,b){K.call(this);this.La=a||1;this.fb=b||p;this.xc=x(this.Hd,this);this.Oc=ta()};y(be,K);h=be.prototype;h.enabled=!1;h.X=null;h.setInterval=function(a){this.La=a;this.X&&this.enabled?(this.stop(),this.start()):this.X&&this.stop()};h.Hd=function(){if(this.enabled){var a=ta()-this.Oc;0<a&&a<.8*this.La?this.X=this.fb.setTimeout(this.xc,this.La-a):(this.X&&(this.fb.clearTimeout(this.X),this.X=null),this.dispatchEvent("tick"),this.enabled&&(this.stop(),this.start()))}};
h.start=function(){this.enabled=!0;this.X||(this.X=this.fb.setTimeout(this.xc,this.La),this.Oc=ta())};h.stop=function(){this.enabled=!1;this.X&&(this.fb.clearTimeout(this.X),this.X=null)};h.f=function(){be.H.f.call(this);this.stop();delete this.fb};var ce=function(a,b,c){if(v(a))c&&(a=x(a,c));else if(a&&"function"==typeof a.handleEvent)a=x(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:p.setTimeout(a,b||0)};var de={MATH:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0},ee=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){if("undefined"===typeof document)return!1;var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);if(!a.firstChild)return!1;b=a.firstChild.firstChild;a.innerHTML=Dc(Ic);return!b.parentElement});var Q=function(a){I.call(this);this.Ja=a;this.g={}};y(Q,I);var fe=[];Q.prototype.Xa=function(a,b,c,d){u(b)||(b&&(fe[0]=b.toString()),b=fe);for(var e=0;e<b.length;e++){var f=ed(a,b[e],c||this.handleEvent,d||!1,this.Ja||this);if(!f)break;this.g[f.key]=f}return this};Q.prototype.Yb=function(a,b,c,d){return ge(this,a,b,c,d)};var ge=function(a,b,c,d,e,f){if(u(c))for(var g=0;g<c.length;g++)ge(a,b,c[g],d,e,f);else{b=dd(b,c,d||a.handleEvent,e,f||a.Ja||a);if(!b)return a;a.g[b.key]=b}return a};
Q.prototype.pc=function(a,b,c,d,e){if(u(b))for(var f=0;f<b.length;f++)this.pc(a,b[f],c,d,e);else if(a=nd(a,b,c||this.handleEvent,w(d)?!!d.capture:!!d,e||this.Ja||this))md(a),delete this.g[a.key]};Q.prototype.ab=function(){La(this.g,function(a,b){this.g.hasOwnProperty(b)&&md(a)},this);this.g={}};Q.prototype.f=function(){Q.H.f.call(this);this.ab()};Q.prototype.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};var he=function(){};he.prototype.yc=null;var je=function(a){var b;(b=a.yc)||(b={},ie(a)&&(b[0]=!0,b[1]=!0),b=a.yc=b);return b};var ke,le=function(){};y(le,he);var me=function(a){return(a=ie(a))?new ActiveXObject(a):new XMLHttpRequest},ie=function(a){if(!a.Lc&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0","MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.Lc=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.Lc};ke=new le;var ne=/^(?:([^:/?#.]+):)?(?:\/\/(?:([^/?#]*)@)?([^/#?]*?)(?::([0-9]+))?(?=[/#?]|$))?([^?#]+)?(?:\?([^#]*))?(?:#([\s\S]*))?$/,oe=function(a){var b=a.match(ne);a=b[1];var c=b[2],d=b[3];b=b[4];var e="";a&&(e+=a+":");d&&(e+="//",c&&(e+=c+"@"),e+=d,b&&(e+=":"+b));return e},pe=function(a,b){if(a){a=a.split("&");for(var c=0;c<a.length;c++){var d=a[c].indexOf("="),e=null;if(0<=d){var f=a[c].substring(0,d);e=a[c].substring(d+1)}else f=a[c];b(f,e?decodeURIComponent(e.replace(/\+/g," ")):"")}}};var R=function(a){this.ca=this.Da=this.ra="";this.Oa=null;this.va=this.aa="";this.P=this.wd=!1;if(a instanceof R){this.P=q(void 0)?void 0:a.P;qe(this,a.ra);var b=a.Da;S(this);this.Da=b;b=a.ca;S(this);this.ca=b;re(this,a.Oa);b=a.aa;S(this);this.aa=b;se(this,a.C.clone());a=a.va;S(this);this.va=a}else a&&(b=String(a).match(ne))?(this.P=!1,qe(this,b[1]||"",!0),a=b[2]||"",S(this),this.Da=te(a),a=b[3]||"",S(this),this.ca=te(a,!0),re(this,b[4]),a=b[5]||"",S(this),this.aa=te(a,!0),se(this,b[6]||"",!0),a=
b[7]||"",S(this),this.va=te(a)):(this.P=!1,this.C=new ue(null,this.P))};
R.prototype.toString=function(){var a=[],b=this.ra;b&&a.push(ve(b,we,!0),":");var c=this.ca;if(c||"file"==b)a.push("//"),(b=this.Da)&&a.push(ve(b,we,!0),"@"),a.push(encodeURIComponent(String(c)).replace(/%25([0-9a-fA-F]{2})/g,"%$1")),c=this.Oa,null!=c&&a.push(":",String(c));if(c=this.aa)this.ca&&"/"!=c.charAt(0)&&a.push("/"),a.push(ve(c,"/"==c.charAt(0)?xe:ye,!0));(c=this.C.toString())&&a.push("?",c);(c=this.va)&&a.push("#",ve(c,ze));return a.join("")};
R.prototype.resolve=function(a){var b=this.clone(),c=!!a.ra;c?qe(b,a.ra):c=!!a.Da;if(c){var d=a.Da;S(b);b.Da=d}else c=!!a.ca;c?(d=a.ca,S(b),b.ca=d):c=null!=a.Oa;d=a.aa;if(c)re(b,a.Oa);else if(c=!!a.aa){if("/"!=d.charAt(0))if(this.ca&&!this.aa)d="/"+d;else{var e=b.aa.lastIndexOf("/");-1!=e&&(d=b.aa.substr(0,e+1)+d)}e=d;if(".."==e||"."==e)d="";else if(-1!=e.indexOf("./")||-1!=e.indexOf("/.")){d=0==e.lastIndexOf("/",0);e=e.split("/");for(var f=[],g=0;g<e.length;){var k=e[g++];"."==k?d&&g==e.length&&
f.push(""):".."==k?((1<f.length||1==f.length&&""!=f[0])&&f.pop(),d&&g==e.length&&f.push("")):(f.push(k),d=!0)}d=f.join("/")}else d=e}c?(S(b),b.aa=d):c=""!==a.C.toString();c?se(b,a.C.clone()):c=!!a.va;c&&(a=a.va,S(b),b.va=a);return b};R.prototype.clone=function(){return new R(this)};
var qe=function(a,b,c){S(a);a.ra=c?te(b,!0):b;a.ra&&(a.ra=a.ra.replace(/:$/,""))},re=function(a,b){S(a);if(b){b=Number(b);if(isNaN(b)||0>b)throw Error("Bad port number "+b);a.Oa=b}else a.Oa=null},se=function(a,b,c){S(a);b instanceof ue?(a.C=b,a.C.mc(a.P)):(c||(b=ve(b,Ae)),a.C=new ue(b,a.P))};R.prototype.getQuery=function(){return this.C.toString()};R.prototype.removeParameter=function(a){S(this);this.C.remove(a);return this};
var S=function(a){if(a.wd)throw Error("Tried to modify a read-only Uri");};R.prototype.mc=function(a){this.P=a;this.C&&this.C.mc(a)};
var te=function(a,b){return a?b?decodeURI(a.replace(/%25/g,"%2525")):decodeURIComponent(a):""},ve=function(a,b,c){return r(a)?(a=encodeURI(a).replace(b,Be),c&&(a=a.replace(/%25([0-9a-fA-F]{2})/g,"%$1")),a):null},Be=function(a){a=a.charCodeAt(0);return"%"+(a>>4&15).toString(16)+(a&15).toString(16)},we=/[#\/\?@]/g,ye=/[#\?:]/g,xe=/[#\?]/g,Ae=/[#\?@]/g,ze=/#/g,ue=function(a,b){this.j=this.i=null;this.L=a||null;this.P=!!b},Ce=function(a){a.i||(a.i=new rb,a.j=0,a.L&&pe(a.L,function(b,c){a.add(decodeURIComponent(b.replace(/\+/g,
" ")),c)}))};h=ue.prototype;h.add=function(a,b){Ce(this);this.L=null;a=De(this,a);var c=this.i.get(a);c||this.i.set(a,c=[]);c.push(b);this.j=xa(this.j)+1;return this};h.remove=function(a){Ce(this);a=De(this,a);return this.i.Ha(a)?(this.L=null,this.j=xa(this.j)-this.i.get(a).length,this.i.remove(a)):!1};h.clear=function(){this.i=this.L=null;this.j=0};h.Ha=function(a){Ce(this);a=De(this,a);return this.i.Ha(a)};
h.forEach=function(a,b){Ce(this);this.i.forEach(function(c,d){Aa(c,function(e){a.call(b,e,d,this)},this)},this)};h.ea=function(){Ce(this);for(var a=this.i.O(),b=this.i.ea(),c=[],d=0;d<b.length;d++)for(var e=a[d],f=0;f<e.length;f++)c.push(b[d]);return c};h.O=function(a){Ce(this);var b=[];if(r(a))this.Ha(a)&&(b=Ga(b,this.i.get(De(this,a))));else{a=this.i.O();for(var c=0;c<a.length;c++)b=Ga(b,a[c])}return b};
h.set=function(a,b){Ce(this);this.L=null;a=De(this,a);this.Ha(a)&&(this.j=xa(this.j)-this.i.get(a).length);this.i.set(a,[b]);this.j=xa(this.j)+1;return this};h.get=function(a,b){if(!a)return b;a=this.O(a);return 0<a.length?String(a[0]):b};
h.toString=function(){if(this.L)return this.L;if(!this.i)return"";for(var a=[],b=this.i.ea(),c=0;c<b.length;c++){var d=b[c],e=encodeURIComponent(String(d));d=this.O(d);for(var f=0;f<d.length;f++){var g=e;""!==d[f]&&(g+="="+encodeURIComponent(String(d[f])));a.push(g)}}return this.L=a.join("&")};h.clone=function(){var a=new ue;a.L=this.L;this.i&&(a.i=this.i.clone(),a.j=this.j);return a};var De=function(a,b){b=String(b);a.P&&(b=b.toLowerCase());return b};
ue.prototype.mc=function(a){a&&!this.P&&(Ce(this),this.L=null,this.i.forEach(function(b,c){var d=c.toLowerCase();c!=d&&(this.remove(c),this.remove(d),0<b.length&&(this.L=null,this.i.set(De(this,d),Ia(b)),this.j=xa(this.j)+b.length))},this));this.P=a};ue.prototype.extend=function(a){for(var b=0;b<arguments.length;b++)vb(arguments[b],function(c,d){this.add(d,c)},this)};var T=function(a){K.call(this);this.headers=new rb;this.Ib=a||null;this.ja=!1;this.Hb=this.b=null;this.Wa=this.Nc=this.rb="";this.ya=this.Ub=this.qb=this.Pb=!1;this.eb=0;this.Cb=null;this.Zc="";this.Fb=this.Cd=this.qc=!1};y(T,K);var Ee=/^https?$/i,Fe=["POST","PUT"],Ge=[];T.prototype.ld=function(){this.Nb();Fa(Ge,this)};
T.prototype.send=function(a,b,c,d){if(this.b)throw Error("[goog.net.XhrIo] Object is active with another request="+this.rb+"; newUri="+a);b=b?b.toUpperCase():"GET";this.rb=a;this.Wa="";this.Nc=b;this.Pb=!1;this.ja=!0;this.b=this.Ib?me(this.Ib):me(ke);this.Hb=this.Ib?je(this.Ib):je(ke);this.b.onreadystatechange=x(this.Tc,this);this.Cd&&"onprogress"in this.b&&(this.b.onprogress=x(function(f){this.Sc(f,!0)},this),this.b.upload&&(this.b.upload.onprogress=x(this.Sc,this)));try{O(this.U,U(this,"Opening Xhr")),
this.Ub=!0,this.b.open(b,String(a),!0),this.Ub=!1}catch(f){O(this.U,U(this,"Error opening Xhr: "+f.message));this.nb(5,f);return}a=c||"";var e=this.headers.clone();d&&vb(d,function(f,g){e.set(g,f)});d=Ea(e.ea());c=p.FormData&&a instanceof p.FormData;!(0<=za(Fe,b))||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,g){this.b.setRequestHeader(g,f)},this);this.Zc&&(this.b.responseType=this.Zc);"withCredentials"in this.b&&this.b.withCredentials!==this.qc&&
(this.b.withCredentials=this.qc);try{He(this),0<this.eb&&(this.Fb=Ie(this.b),O(this.U,U(this,"Will abort after "+this.eb+"ms if incomplete, xhr2 "+this.Fb)),this.Fb?(this.b.timeout=this.eb,this.b.ontimeout=x(this.ad,this)):this.Cb=ce(this.ad,this.eb,this)),O(this.U,U(this,"Sending request")),this.qb=!0,this.b.send(a),this.qb=!1}catch(f){O(this.U,U(this,"Send error: "+f.message)),this.nb(5,f)}};
var Ie=function(a){return G&&Ub(9)&&ha(a.timeout)&&q(a.ontimeout)},Da=function(a){return"content-type"==a.toLowerCase()};T.prototype.ad=function(){"undefined"!=typeof fa&&this.b&&(this.Wa="Timed out after "+this.eb+"ms, aborting",O(this.U,U(this,this.Wa)),this.dispatchEvent("timeout"),this.abort(8))};T.prototype.nb=function(a,b){this.ja=!1;this.b&&(this.ya=!0,this.b.abort(),this.ya=!1);this.Wa=b;Je(this);Ke(this)};var Je=function(a){a.Pb||(a.Pb=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))};
T.prototype.abort=function(){this.b&&this.ja&&(O(this.U,U(this,"Aborting")),this.ja=!1,this.ya=!0,this.b.abort(),this.ya=!1,this.dispatchEvent("complete"),this.dispatchEvent("abort"),Ke(this))};T.prototype.f=function(){this.b&&(this.ja&&(this.ja=!1,this.ya=!0,this.b.abort(),this.ya=!1),Ke(this,!0));T.H.f.call(this)};T.prototype.Tc=function(){this.la||(this.Ub||this.qb||this.ya?Le(this):this.zd())};T.prototype.zd=function(){Le(this)};
var Le=function(a){if(a.ja&&"undefined"!=typeof fa)if(a.Hb[1]&&4==Me(a)&&2==Ne(a))O(a.U,U(a,"Local request error detected and ignored"));else if(a.qb&&4==Me(a))ce(a.Tc,0,a);else if(a.dispatchEvent("readystatechange"),4==Me(a)){O(a.U,U(a,"Request complete"));a.ja=!1;try{if(Oe(a))a.dispatchEvent("complete"),a.dispatchEvent("success");else{try{var b=2<Me(a)?a.b.statusText:""}catch(c){O(a.U,"Can not get status: "+c.message),b=""}a.Wa=b+" ["+Ne(a)+"]";Je(a)}}finally{Ke(a)}}};
T.prototype.Sc=function(a,b){A("progress"===a.type,"goog.net.EventType.PROGRESS is of the same type as raw XHR progress.");this.dispatchEvent(Pe(a,"progress"));this.dispatchEvent(Pe(a,b?"downloadprogress":"uploadprogress"))};
var Pe=function(a,b){return{type:b,lengthComputable:a.lengthComputable,loaded:a.loaded,total:a.total}},Ke=function(a,b){if(a.b){He(a);var c=a.b,d=a.Hb[0]?la:null;a.b=null;a.Hb=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){M(a.U,"Problem encountered resetting onreadystatechange: "+e.message)}}},He=function(a){a.b&&a.Fb&&(a.b.ontimeout=null);a.Cb&&(p.clearTimeout(a.Cb),a.Cb=null)};T.prototype.Wb=function(){return!!this.b};
var Oe=function(a){var b=Ne(a);a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}if(!c){if(b=0===b)a=String(a.rb).match(ne)[1]||null,!a&&p.self&&p.self.location&&(a=p.self.location.protocol,a=a.substr(0,a.length-1)),b=!Ee.test(a?a.toLowerCase():"");c=b}return c},Me=function(a){return a.b?a.b.readyState:0},Ne=function(a){try{return 2<Me(a)?a.b.status:-1}catch(b){return-1}},Qe=function(a){try{return a.b?a.b.responseText:""}catch(b){return O(a.U,
"Can not get responseText: "+b.message),""}};T.prototype.getResponseHeader=function(a){if(this.b&&4==Me(this))return a=this.b.getResponseHeader(a),null===a?void 0:a};T.prototype.getAllResponseHeaders=function(){return this.b&&4==Me(this)?this.b.getAllResponseHeaders()||"":""};var U=function(a,b){return b+" ["+a.Nc+" "+a.rb+" "+Ne(a)+"]"};new K;new Kc;var Se=function(a,b,c){function d(g){g&&b.appendChild(r(g)?a.createTextNode(g):g)}for(var e=1;e<c.length;e++){var f=c[e];!ma(f)||w(f)&&0<f.nodeType?d(f):Aa(Re(f)?Ia(f):f,d)}},Te=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null},Re=function(a){if(a&&"number"==typeof a.length){if(w(a))return"function"==typeof a.item||"string"==typeof a.item;if(v(a))return"function"==typeof a.item}return!1},Ue=function(){this.Ra=p.document||document};h=Ue.prototype;
h.getElementsByTagName=function(a,b){return(b||this.Ra).getElementsByTagName(String(a))};h.createElement=function(a){return this.Ra.createElement(String(a))};h.createTextNode=function(a){return this.Ra.createTextNode(String(a))};h.h=function(){var a=this.Ra;return a.parentWindow||a.defaultView};h.appendChild=function(a,b){A(null!=a&&null!=b,"goog.dom.appendChild expects non-null arguments");a.appendChild(b)};
h.append=function(a,b){var c=a;A(c,"Node cannot be null or undefined.");Se(9==c.nodeType?c:c.ownerDocument||c.document,a,arguments)};h.canHaveChildren=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
h.removeNode=Te;h.contains=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};var Ve=function(){};var We=function(a,b){this.bd=!!b};y(We,Ve);We.prototype.Bb=function(a){var b=new Xe;Ye(this,a,b);return b.toString()};
var Ye=function(a,b,c){var d=eb(b.A());Aa(d,function(e){if(b.has(e)){A(e.wa()==b.A(),"The current message does not contain the given field");var f=e.W;f=b.Z[f].Xb?null!=b.J[f]?b.J[f].length:0:null!=b.J[f]?1:0;for(var g=0;g<f;++g){c.append(e.getName());11==e.da||10==e.da?(c.append(" {"),Ze(c),c.na+=2):c.append(": ");$e(this,b.get(e,g),e,c);if(11==e.da||10==e.da)af(c),c.append("}");Ze(c)}}},a);hb(b,function(e,f){bf(this,e,f,A(c))},a)},bf=function(a,b,c,d){if(null!=c)if(u(c))Aa(c,function(g){bf(this,
b,g,d)},a);else{if(w(c)){d.append(b);d.append(" {");Ze(d);d.na+=2;if(c instanceof gb)Ye(a,c,d);else for(var e in c){var f=cb(e);A(isFinite(f)&&0==f%1);bf(a,f,c[e],d)}af(d);d.append("}")}else r(c)&&(c=bb(c)),d.append(b),d.append(": "),d.append(c.toString());Ze(d)}},$e=function(a,b,c,d){switch(c.da){case 1:case 2:case 3:case 4:case 5:case 13:case 6:case 7:case 8:case 15:case 16:case 17:case 18:d.append(b);break;case 12:case 9:b=bb(b.toString());d.append(b);break;case 14:if(!a.bd){var e=!1;La(c.ac,function(f,
g){e||f!=b||(d.append(g),e=!0)})}e&&!a.bd||d.append(b.toString());break;case 10:case 11:Ye(a,b,d)}},Xe=function(){this.na=0;this.kb=[];this.jc=!0};Xe.prototype.toString=function(){return this.kb.join("")};var af=function(a){a.na-=2;A(0<=a.na)};Xe.prototype.append=function(a){if(this.jc){for(var b=0;b<this.na;++b)this.kb.push(" ");this.jc=!1}this.kb.push(a.toString())};var Ze=function(a){a.kb.push("\n");a.jc=!0};var cf=new We;gb.prototype.toString=function(){return cf.Bb(this)};var df=new nb,ef=new D;C(ef,1,3);C(ef,2,2);C(df,1,ef);var ff=new D;C(ff,1,3);C(ff,2,2);var gf=new D;C(gf,1,3);C(gf,2,2);(function(){if(Jb){var a=/Windows NT ([0-9.]+)/;return(a=a.exec(E))?a[1]:"0"}return Ib?(a=/10[_.][0-9_.]+/,(a=a.exec(E))?a[0].replace(/_/g,"."):"10"):Kb?(a=/Android\s+([^\);]+)(\)|;)/,(a=a.exec(E))?a[1]:""):Lb||Mb||Nb?(a=/(?:iPhone|CPU)\s+OS\s+(\S+)/,(a=a.exec(E))?a[1].replace(/_/g,"."):""):""})();var hf=function(a,b,c){I.call(this);this.Zb=a;this.La=b||0;this.Ja=c;this.kd=x(this.qd,this)};y(hf,I);h=hf.prototype;h.u=0;h.f=function(){hf.H.f.call(this);this.stop();delete this.Zb;delete this.Ja};h.start=function(a){this.stop();this.u=ce(this.kd,q(a)?a:this.La)};h.stop=function(){this.Wb()&&p.clearTimeout(this.u);this.u=0};h.Wb=function(){return 0!=this.u};h.qd=function(){this.u=0;this.Zb&&this.Zb.call(this.Ja)};var jf=function(){I.call(this);this.lc={}};y(jf,I);jf.prototype.connect=function(a){a&&a()};jf.prototype.isConnected=function(){return!0};jf.prototype.f=function(){jf.H.f.call(this);delete this.lc;delete this.Ec};var L={};var kf={1:"NativeMessagingTransport",2:"FrameElementMethodTransport",3:"IframeRelayTransport",4:"IframePollingTransport",5:"FlashTransport",6:"NixTransport",7:"DirectTransport"},lf=["pu","lru","pru","lpu","ppu"],V={},nf=function(){for(var a=10,b=mf,c=b.length,d="";0<a--;)d+=b.charAt(Math.floor(Math.random()*c));return d},mf="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";var W=function(a){I.call(this);this.Y=a||ua||(ua=new Ue)};y(W,I);W.prototype.Qa=0;W.prototype.h=function(){return this.Y.h()};W.prototype.getName=function(){return kf[String(this.Qa)]||""};/*
 Portions of this code are from MochiKit, received by
 The Closure Authors under the MIT license. All other code is Copyright
 2005-2009 The Closure Authors. All Rights Reserved.
*/
var X=function(){this.Ab=[];this.Rc=void 0;this.Dc=null;this.Ua=this.N=!1;this.ha=void 0;this.nc=this.wc=this.Kb=!1;this.Eb=0;this.v=null;this.jb=0};X.prototype.cancel=function(a){if(this.N)this.ha instanceof X&&this.ha.cancel();else{if(this.v){var b=this.v;delete this.v;a?b.cancel(a):(b.jb--,0>=b.jb&&b.cancel())}this.Rc?this.Rc.call(this.Dc,this):this.nc=!0;this.N||this.Gc(new of(this))}};X.prototype.Cc=function(a,b){this.Kb=!1;pf(this,a,b)};
var pf=function(a,b,c){a.N=!0;a.ha=c;a.Ua=!b;qf(a)},sf=function(a){if(a.N){if(!a.nc)throw new rf(a);a.nc=!1}};X.prototype.M=function(a){sf(this);tf(a);pf(this,!0,a)};X.prototype.Gc=function(a){sf(this);tf(a);pf(this,!1,a)};var tf=function(a){A(!(a instanceof X),"An execution sequence may not be initiated with a blocking Deferred.")},vf=function(a,b,c){uf(a,b,null,c)},uf=function(a,b,c,d){A(!a.wc,"Blocking Deferreds can not be re-used");a.Ab.push([b,c,d]);a.N&&qf(a)};
X.prototype.then=function(a,b,c){var d,e,f=new P(function(g,k){d=g;e=k});uf(this,d,function(g){g instanceof of?f.cancel():e(g)});return f.then(a,b,c)};X.prototype.$goog_Thenable=!0;var wf=function(a,b){b instanceof X?vf(a,x(b.jd,b)):vf(a,function(){return b})};X.prototype.jd=function(a){var b=new X;uf(this,b.M,b.Gc,b);a&&(b.v=this,this.jb++);return b};
var xf=function(a){return Ca(a.Ab,function(b){return v(b[1])})},qf=function(a){if(a.Eb&&a.N&&xf(a)){var b=a.Eb,c=yf[b];c&&(p.clearTimeout(c.u),delete yf[b]);a.Eb=0}a.v&&(a.v.jb--,delete a.v);b=a.ha;for(var d=c=!1;a.Ab.length&&!a.Kb;){var e=a.Ab.shift(),f=e[0],g=e[1];e=e[2];if(f=a.Ua?g:f)try{var k=f.call(e||a.Dc,b);q(k)&&(a.Ua=a.Ua&&(k==b||k instanceof Error),a.ha=b=k);if(Md(b)||"function"===typeof p.Promise&&b instanceof p.Promise)d=!0,a.Kb=!0}catch(l){b=l,a.Ua=!0,xf(a)||(c=!0)}}a.ha=b;d&&(k=x(a.Cc,
a,!0),d=x(a.Cc,a,!1),b instanceof X?(uf(b,k,d),b.wc=!0):b.then(k,d));c&&(b=new zf(b),yf[b.u]=b,a.Eb=b.u)},rf=function(){z.call(this)};y(rf,z);rf.prototype.message="Deferred has already fired";rf.prototype.name="AlreadyCalledError";var of=function(){z.call(this)};y(of,z);of.prototype.message="Deferred was canceled";of.prototype.name="CanceledError";var zf=function(a){this.u=p.setTimeout(x(this.Gd,this),0);this.nb=a};
zf.prototype.Gd=function(){A(yf[this.u],"Cannot throw an error that is not scheduled.");delete yf[this.u];throw this.nb;};var yf={};var Bf=function(a,b){W.call(this,b);this.a=a;this.Ia=new Q(this);Lc(this,sa(J,this.Ia));this.$=new be(100,this.h());Lc(this,sa(J,this.$));this.D=new X;this.F=new X;this.w=new X;this.Ob=nf();this.qa=null;this.Fa={};this.Ad=this.a.name;Af(this.a,this.a.name+"_"+Y(this.a));this.Va=!1;wf(this.w,this.D);wf(this.w,this.F);vf(this.w,this.bc,this);this.w.M(!0);this.Ia.Xa(this.$,"tick",this.Ya);N("DirectTransport created. role="+Y(this.a))};y(Bf,W);
var Cf={},Ff=function(a){var b=new Df(a.channelName,a.service,a.payload);a=b.Lb;var c=b.kc;b=b.Za;O(L.c,"messageReceived: channel="+a+", service="+c+", payload="+b);var d=V[a];if(d)return d.ia(c,b),!0;d=Ef(b)[0];for(var e in V){var f=V[e];if(1==Y(f)&&!f.isConnected()&&"tp"==c&&"SETUP"==d)return Af(f,a),f.ia(c,b),!0}N("channel name mismatch; message ignored.");return!1};h=Bf.prototype;h.Qa=7;
h.Db=function(a){a=Ef(a);var b=a[1];switch(a[0]){case "SETUP_ACK":this.D.N||this.D.M(!0);break;case "SETUP":this.zb(),null!=this.qa&&this.qa!=b&&(N("Sending SETUP and changing peer ID to: "+b),this.bb()),this.qa=b}};h.bb=function(){this.send("tp","SETUP,"+this.Ob)};h.zb=function(){this.send("tp","SETUP_ACK");this.F.N||this.F.M(!0)};
h.connect=function(){var a=this.h();if(a){var b=pa(a);0==(Cf[b]||0)&&null==ka("crosswindowmessaging.channel",a)&&ia("crosswindowmessaging.channel",Ff,a);Cf[b]++;this.Va=!0;this.Ya()}else O(L.c,"connect(): no window to initialize.")};h.Ya=function(){this.a.isConnected()?this.$.stop():(this.$.start(),this.bb())};h.send=function(a,b){this.a.R?(a=new Df(this.Ad+"_"+(0==Y(this.a)?1:0),a,b),this.a.m.directSyncMode?this.Hc(a):this.Fa[pa(a)]=ce(x(this.Hc,this,a),0)):O(L.c,"send(): window not ready")};
h.Hc=function(a){var b=pa(a);this.Fa[b]&&delete this.Fa[b];try{var c=ka("crosswindowmessaging.channel",this.a.R)}catch(d){(a=L.c)&&a.sa("Can't access other window, ignoring.",d);return}if(null===c)(a=L.c)&&a.sa("Peer window had no global function.",void 0);else try{c({channelName:a.Lb,service:a.kc,payload:a.Za}),N("send(): channelName="+a.Lb+" service="+a.kc+" payload="+a.Za)}catch(d){(a=L.c)&&a.sa("Error performing call, ignoring.",d)}};h.bc=function(){Gf(this.a,0)};
h.f=function(){if(this.Va){var a=this.h(),b=pa(a);1==--Cf[b]&&ia("crosswindowmessaging.channel",null,a)}this.Fa&&(La(this.Fa,function(c){p.clearTimeout(c)}),this.Fa=null);this.D&&(this.D.cancel(),delete this.D);this.F&&(this.F.cancel(),delete this.F);this.w&&(this.w.cancel(),delete this.w);Bf.H.f.call(this)};var Ef=function(a){a=a.split(",");a[1]=a[1]||null;return a},Df=function(a,b,c){this.Lb=a;this.kc=b;this.Za=c};var Hf=function(a,b){W.call(this,b);this.a=a;this.$a=[];this.od=x(this.pd,this)};y(Hf,W);h=Hf.prototype;h.Qa=2;h.ic=!1;h.connect=function(){0==Y(this.a)?(this.fa=this.a.Ka,this.fa.XPC_toOuter=x(this.Mc,this)):this.uc()};
h.uc=function(){var a=!0;try{this.fa||(this.fa=this.h().frameElement),this.fa&&this.fa.XPC_toOuter&&(this.cc=this.fa.XPC_toOuter,this.fa.XPC_toOuter.XPC_toInner=x(this.Mc,this),a=!1,this.send("tp","SETUP_ACK"),Gf(this.a))}catch(b){M(L.c,"exception caught while attempting setup: "+b)}a&&(this.tc||(this.tc=x(this.uc,this)),this.h().setTimeout(this.tc,100))};
h.Db=function(a){if(0!=Y(this.a)||this.a.isConnected()||"SETUP_ACK"!=a)throw Error("Got unexpected transport message.");this.cc=this.fa.XPC_toOuter.XPC_toInner;Gf(this.a)};h.Mc=function(a,b){this.ic||0!=this.$a.length?(this.$a.push({Ed:a,Za:b}),1==this.$a.length&&this.h().setTimeout(this.od,1)):this.a.ia(a,b)};h.pd=function(){for(;this.$a.length;){var a=this.$a.shift();this.a.ia(a.Ed,a.Za)}};h.send=function(a,b){this.ic=!0;this.cc(a,b);this.ic=!1};
h.f=function(){Hf.H.f.call(this);this.fa=this.cc=null};var Jf=function(a,b){W.call(this,b);this.a=a;this.Bd=this.a.m.pru;this.Vc=this.a.m.ifrid;Hb&&If()};y(Jf,W);if(Hb)var Kf=[],Lf=0,If=function(){Lf||(Lf=window.setTimeout(function(){Mf()},1E3))},Mf=function(a){var b=ta();for(a=a||3E3;Kf.length&&b-Kf[0].timestamp>=a;){var c=Kf.shift().vd;Te(c);yd("iframe removed")}Lf=window.setTimeout(Nf,1E3)},Nf=function(){Mf()};var Of={};Jf.prototype.Qa=3;Jf.prototype.connect=function(){this.h().xpcRelay||(this.h().xpcRelay=Pf);this.send("tp","SETUP")};
var Pf=function(a,b){var c=b.indexOf(":"),d=b.substr(0,c);b=b.substr(c+1);if(G&&-1!=(c=d.indexOf("|"))){g=d.substr(0,c);d=d.substr(c+1);c=d.indexOf("+");var e=d.substr(0,c);c=parseInt(d.substr(c+1),10);var f=Of[e];f||(f=Of[e]={Jc:[],Wc:0,Ic:0});-1!=d.indexOf("++")&&(f.Ic=c+1);f.Jc[c]=b;f.Wc++;if(f.Wc!=f.Ic)return;b=f.Jc.join("");delete Of[e]}else var g=d;V[a].ia(g,decodeURIComponent(b))};Jf.prototype.Db=function(a){"SETUP"==a?(this.send("tp","SETUP_ACK"),Gf(this.a)):"SETUP_ACK"==a&&Gf(this.a)};
Jf.prototype.send=function(a,b){b=encodeURIComponent(b);var c=b.length;if(G&&1800<c)for(var d=Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^ta()).toString(36),e=0,f=0;e<c;f++){var g=b.substr(e,1800);e+=1800;Qf(this,a,g,d+(e>=c?"++":"+")+f)}else Qf(this,a,b)};
var Qf=function(a,b,c,d){if(G){var e=a.h().document.createElement("DIV"),f={src:null,srcdoc:null},g={onload:new ec(cc,"this.xpcOnload()"),sandbox:null},k={sandbox:""};var l={};for(var m in f)A(m.toLowerCase()==m,"Must be lower case"),l[m]=f[m];for(m in k)A(m.toLowerCase()==m,"Must be lower case"),l[m]=k[m];for(m in g){var n=m.toLowerCase();if(n in f)throw Error('Cannot override "'+n+'" attribute, got "'+m+'" with value "'+g[m]+'"');n in k&&delete l[n];l[m]=g[m]}f=null;g="";if(l)for(ja in l){if(!Ec.test(ja))throw Error('Invalid attribute name "'+
ja+'".');m=l[ja];if(null!=m){k=ja;n=m;if(n instanceof ec)n=fc(n);else if("style"==k.toLowerCase()){m=void 0;if(!w(n))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof n+" given: "+n);if(!(n instanceof H)){var Ac="";for(m in n){if(!/^[-_a-zA-Z0-9]+$/.test(m))throw Error("Name allows only [-_a-zA-Z0-9], got: "+m);var Ha=n[m];null!=Ha&&(Ha=u(Ha)?Ba(Ha,sc).join(" "):sc(Ha),Ac+=m+":"+Ha+";")}n=Ac?(new H).oa(Ac):qc}n instanceof H&&n.constructor===H&&n.dd===
pc?m=n.vb:(B("expected object of type SafeStyle, got '"+n+"' of type "+t(n)),m="type_error:SafeStyle");n=m}else{if(/^on/i.test(k))throw Error('Attribute "'+k+'" requires goog.string.Const value, "'+n+'" given.');if(k.toLowerCase()in Fc)if(n instanceof ic)n instanceof ic&&n.constructor===ic&&n.gd===hc?m=n.hc:(B("expected object of type TrustedResourceUrl, got '"+n+"' of type "+t(n)),m="type_error:TrustedResourceUrl"),n=m.toString();else if(n instanceof kc)n=lc(n).toString();else if(r(n))n=oc(n).T();
else throw Error('Attribute "'+k+'" on tag "iframe" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+n+'" given.');}n.ga&&(n=n.T());A(r(n)||ha(n),"String or number value expected, got "+typeof n+" with value: "+n);k=k+'="'+Ya(String(n))+'"';g+=" "+k}}var ja="<iframe"+g;g=void 0;null!=g?u(g)||(g=[g]):g=[];!0===bc.iframe?(A(!g.length,"Void tag <iframe> does not allow content."),ja+=">"):(f=Hc(g),ja+=">"+Dc(f).toString()+"</iframe>",f=f.Sa());(l=l&&l.dir)&&(f=/^(ltr|rtl|auto)$/i.test(l)?
0:null);l=Gc(ja,f);if(de[e.tagName.toUpperCase()])throw Error("goog.dom.safe.setInnerHtml cannot be used to set content of "+e.tagName+".");if(ee())for(;e.lastChild;)e.removeChild(e.lastChild);e.innerHTML=Dc(l);e=e.childNodes[0];e.xpcOnload=Rf}else e=a.h().document.createElement("IFRAME"),Hb?Kf.push({timestamp:ta(),vd:e}):ed(e,"load",Rf);l=e.style;l.visibility="hidden";l.width=e.style.height="0px";l.position="absolute";l=a.Bd;l+="#"+a.a.name;a.Vc&&(l+=","+a.Vc);l+="|"+b;d&&(l+="|"+d);l+=":"+c;e.src=
l;a.h().document.body.appendChild(e);yd("msg sent: "+l)},Rf=function(){yd("iframe-load");Te(this)};Jf.prototype.f=function(){Jf.H.f.call(this);Hb&&Mf(0)};var Z=function(a,b,c,d,e){W.call(this,c);this.a=a;this.V=e||2;A(1<=this.V);A(2>=this.V);this.Uc=b||"*";this.Ia=new Q(this);this.$=new be(100,this.h());this.tb=!!d;this.D=new X;this.F=new X;this.w=new X;this.Ob=nf();this.qa=null;this.tb?1==Y(this.a)?wf(this.w,this.D):wf(this.w,this.F):(wf(this.w,this.D),2==this.V&&wf(this.w,this.F));vf(this.w,this.bc,this);this.w.M(!0);this.Ia.Xa(this.$,"tick",this.Ya);N("NativeMessagingTransport created.  protocolVersion="+this.V+", oneSidedHandshake="+this.tb+", role="+
Y(this.a))};y(Z,W);Z.prototype.G=null;Z.prototype.Va=!1;Z.prototype.Qa=1;var Sf={};Z.prototype.cb=0;
var Vf=function(a){var b=a.ma.data;if(!r(b))return!1;var c=b.indexOf("|"),d=b.indexOf(":");if(-1==c||-1==d)return!1;var e=b.substring(0,c);c=b.substring(c+1,d);b=b.substring(d+1);O(L.c,"messageReceived: channel="+e+", service="+c+", payload="+b);if(d=V[e])return d.ia(c,b,a.ma.origin),!0;d=Tf(b)[0];for(var f in V){var g=V[f];if(1==Y(g)&&!g.isConnected()&&"tp"==c&&("SETUP"==d||"SETUP_NTPV2"==d)&&Uf(g,a.ma.origin))return Af(g,e),g.ia(c,b),!0}N('channel name mismatch; message ignored"');return!1};
Z.prototype.Db=function(a){var b=Tf(a);a=b[1];switch(b[0]){case "SETUP_ACK":Wf(this,1);this.D.N||this.D.M(!0);break;case "SETUP_ACK_NTPV2":2==this.V&&(Wf(this,2),this.D.N||this.D.M(!0));break;case "SETUP":Wf(this,1);this.zb(1);break;case "SETUP_NTPV2":2==this.V&&(b=this.G,Wf(this,2),this.zb(2),1!=b&&null==this.qa||this.qa==a||(N("Sending SETUP and changing peer ID to: "+a),this.bb()),this.qa=a)}};
Z.prototype.bb=function(){A(!(1==this.V&&2==this.G));2!=this.V||null!=this.G&&2!=this.G||this.send("tp","SETUP_NTPV2,"+this.Ob);null!=this.G&&1!=this.G||this.send("tp","SETUP")};Z.prototype.zb=function(a){A(1!=this.V||2!=a,"Shouldn't try to send a v2 setup ack in v1 mode.");if(2!=this.V||null!=this.G&&2!=this.G||2!=a){if(null!=this.G&&1!=this.G||1!=a)return;this.send("tp","SETUP_ACK")}else this.send("tp","SETUP_ACK_NTPV2");this.F.N||this.F.M(!0)};
var Wf=function(a,b){b>a.G&&(a.G=b);1==a.G&&(a.F.N||a.tb||a.F.M(!0),a.qa=null)};h=Z.prototype;h.connect=function(){var a=this.h(),b=pa(a),c=Sf[b];ha(c)||(c=0);0==c&&ed(a.postMessage?a:a.document,"message",Vf,!1,Z);Sf[b]=c+1;this.Va=!0;this.Ya()};h.Ya=function(){var a=0==Y(this.a);this.tb&&a||this.a.isConnected()||this.la?this.$.stop():(this.$.start(),this.bb())};
h.send=function(a,b){var c=this.a.R;c?(this.send=function(d,e){var f=this,g=this.a.name;this.cb=ce(function(){f.cb=0;try{var k=c.postMessage?c:c.document;if(k.postMessage)k.postMessage(g+"|"+d+":"+e,f.Uc),O(L.c,"send(): service="+d+" payload="+e+" to hostname="+f.Uc);else{var l=L.c;l&&l.sa("Peer window had no postMessage function.",void 0)}}catch(m){(k=L.c)&&k.sa("Error performing postMessage, ignoring.",m)}},0)},this.send(a,b)):O(L.c,"send(): window not ready")};
h.bc=function(){Gf(this.a,1==this.V||1==this.G?200:void 0)};h.f=function(){if(this.Va){var a=this.h(),b=pa(a),c=Sf[b];Sf[b]=c-1;1==c&&ld(a.postMessage?a:a.document,"message",Vf,!1,Z)}this.cb&&(p.clearTimeout(this.cb),this.cb=0);J(this.Ia);delete this.Ia;J(this.$);delete this.$;this.D.cancel();delete this.D;this.F.cancel();delete this.F;this.w.cancel();delete this.w;delete this.send;Z.H.f.call(this)};var Tf=function(a){a=a.split(",");a[1]=a[1]||null;return a};var Xf=function(a,b){W.call(this,b);this.a=a;this.vc=a.at||"";this.Yc=a.rat||"";a=this.h();if(!a.nix_setup_complete)try{a.execScript("Class GCXPC____NIXVBS_wrapper\n Private m_Transport\nPrivate m_Auth\nPublic Sub SetTransport(transport)\nIf isEmpty(m_Transport) Then\nSet m_Transport = transport\nEnd If\nEnd Sub\nPublic Sub SetAuth(auth)\nIf isEmpty(m_Auth) Then\nm_Auth = auth\nEnd If\nEnd Sub\nPublic Function GetAuthToken()\n GetAuthToken = m_Auth\nEnd Function\nPublic Sub SendMessage(service, payload)\n Call m_Transport.GCXPC____NIXJS_handle_message(service, payload)\nEnd Sub\nPublic Sub CreateChannel(channel)\n Call m_Transport.GCXPC____NIXJS_create_channel(channel)\nEnd Sub\nPublic Sub GCXPC____NIXVBS_container()\n End Sub\nEnd Class\n Function GCXPC____NIXVBS_get_wrapper(transport, auth)\nDim wrap\nSet wrap = New GCXPC____NIXVBS_wrapper\nwrap.SetTransport transport\nwrap.SetAuth auth\nSet GCXPC____NIXVBS_get_wrapper = wrap\nEnd Function",
"vbscript"),a.nix_setup_complete=!0}catch(c){M(L.c,"exception caught while attempting global setup: "+c)}this.GCXPC____NIXJS_handle_message=this.ud;this.GCXPC____NIXJS_create_channel=this.md};y(Xf,W);h=Xf.prototype;h.Qa=6;h.Ma=!1;h.pa=null;h.connect=function(){0==Y(this.a)?this.sc():this.rc()};
h.sc=function(){if(!this.Ma){var a=this.a.Ka;try{a.contentWindow.opener=(0,this.h().GCXPC____NIXVBS_get_wrapper)(this,this.vc),this.Ma=!0}catch(b){M(L.c,"exception caught while attempting setup: "+b)}this.Ma||this.h().setTimeout(x(this.sc,this),100)}};
h.rc=function(){if(!this.Ma){try{var a=this.h().opener;if(a&&"GCXPC____NIXVBS_container"in a){this.pa=a;if(this.pa.GetAuthToken()!=this.Yc){M(L.c,"Invalid auth token from other party");return}this.pa.CreateChannel((0,this.h().GCXPC____NIXVBS_get_wrapper)(this,this.vc));this.Ma=!0;Gf(this.a)}}catch(b){M(L.c,"exception caught while attempting setup: "+b);return}this.Ma||this.h().setTimeout(x(this.rc,this),100)}};
h.md=function(a){"unknown"==typeof a&&"GCXPC____NIXVBS_container"in a||M(L.c,"Invalid NIX channel given to createChannel_");this.pa=a;this.pa.GetAuthToken()!=this.Yc?M(L.c,"Invalid auth token from other party"):Gf(this.a)};h.ud=function(a,b){this.h().setTimeout(x(function(){this.a.ia(a,b)},this),1)};h.send=function(a,b){"unknown"!==typeof this.pa&&M(L.c,"NIX channel not connected");this.pa.SendMessage(a,b)};h.f=function(){Xf.H.f.call(this);this.pa=null};var Zf=function(a,b){jf.call(this);for(var c=0,d;d=lf[c];c++)if(d in a&&!/^https?:\/\//.test(a[d]))throw Error("URI "+a[d]+" is invalid for field "+d);this.m=a;this.name=this.m.cn||nf();this.Y=b||ua||(ua=new Ue);this.mb=[];this.ec=new Q(this);a.lpu=a.lpu||oe(this.Y.h().location.href)+"/robots.txt";a.ppu=a.ppu||oe(a.pu||"")+"/robots.txt";V[this.name]=this;nd(window,"unload",Yf)||dd(window,"unload",Yf);N("CrossPageChannel created: "+this.name)};y(Zf,jf);var $f=/^%*tp$/,ag=/^%+tp$/;h=Zf.prototype;
h.ka=null;h.Ba=null;h.I=null;h.l=1;h.isConnected=function(){return 2==this.l};h.R=null;h.Ka=null;h.connect=function(a){this.Mb=a||la;3==this.l&&(this.l=1);this.Ba?vf(this.Ba,this.Bc):this.Bc()};
h.Bc=function(){N("continueConnection_()");this.Ba=null;if(this.m.ifrid){var a=this.m.ifrid;this.Ka=r(a)?this.Y.Ra.getElementById(a):a}this.Ka&&((a=this.Ka.contentWindow)||(a=window.frames[this.m.ifrid]),this.R=a);if(!this.R){if(window==window.top)throw Error("CrossPageChannel: Can't connect, peer window-object not set.");this.R=window.parent}if(!this.I){if(!this.m.tp){a=this.m;if(v(document.postMessage)||v(window.postMessage)||G&&window.postMessage)var b=1;else if(Gb)b=2;else if(G&&this.m.pru)b=
3;else{var c;if(c=G){c=!1;try{b=window.opener,window.opener={},c=Bb(window,"opener"),window.opener=b}catch(d){}}b=c?6:0}a.tp=b}if(v(this.m.tp))this.I=new this.m.tp(this,this.Y);else switch(this.m.tp){case 1:this.I=new Z(this,this.m.ph,this.Y,!!this.m.osh,this.m.nativeProtocolVersion||2);break;case 6:this.I=new Xf(this,this.Y);break;case 2:this.I=new Hf(this,this.Y);break;case 3:this.I=new Jf(this,this.Y);break;case 7:if(a=this.R)try{a=window.document.domain==this.R.document.domain}catch(d){a=!1}a?
this.I=new Bf(this,this.Y):N("DirectTransport not supported for this window, peer window in different security context or not set yet.")}if(this.I)N("Transport created: "+this.I.getName());else throw Error("CrossPageChannel: No suitable transport found! You may try injecting a Transport constructor directly via the channel config object.");}for(this.I.connect();0<this.mb.length;)this.mb.shift()()};
h.close=function(){this.Ba&&(this.Ba.cancel(),this.Ba=null);this.mb.length=0;this.ec.ab();this.l=3;J(this.I);this.Mb=this.I=null;J(this.ka);this.ka=null;N('Channel "'+this.name+'" closed')};var Gf=function(a,b){a.isConnected()||a.ka&&a.ka.Wb()||(a.l=2,N('Channel "'+a.name+'" connected'),J(a.ka),q(b)?(a.ka=new hf(a.Mb,b),a.ka.start()):(a.ka=null,a.Mb()))};
Zf.prototype.send=function(a,b){if(this.isConnected()){try{var c=!!this.R&&!this.R.closed}catch(d){c=!1}c?(w(b)&&(b=(new td).Bb(b)),this.I.send(bg(a),b)):(M(L.c,"Peer has disappeared."),this.close())}else M(L.c,"Can't send. Channel not connected.")};
Zf.prototype.ia=function(a,b,c){if(this.Ba)this.mb.push(x(this.ia,this,a,b,c));else if(Uf(this,c))if(this.la||3==this.l)(b=L.c)&&b.sa("CrossPageChannel::xpcDeliver(): Channel closed.",void 0);else if(a&&"tp"!=a)if(this.isConnected()){if(c=a.replace(/%[0-9a-f]{2}/gi,decodeURIComponent),c=ag.test(c)?c.substring(1):c,a=this.lc[c],a||(this.Ec?a={M:sa(this.Ec,c),Qc:w(b)}:((a=this.c)&&a.sa('Unknown service name "'+c+'"',void 0),a=null)),a){a:{var d=a.Qc;if(d&&r(b))try{var e=JSON.parse(b);break a}catch(f){(e=
this.c)&&e.sa("Expected JSON payload for "+c+', was "'+b+'"',void 0);e=null;break a}else if(!d&&!r(b)){e=(new td).Bb(b);break a}e=b}null!=e&&a.M(e)}}else N("CrossPageChannel::xpcDeliver(): Not connected.");else this.I.Db(b);else(b=L.c)&&b.sa('Message received from unapproved origin "'+c+'" - rejected.',void 0)};
var bg=function(a){$f.test(a)&&(a="%"+a);return a.replace(/[%:|]/g,encodeURIComponent)},Y=function(a){var b=a.m.role;return ha(b)?b:window.parent==a.R?1:0},Af=function(a,b){O(L.c,"changing channel name to "+b);delete V[a.name];a.name=b;V[b]=a},Uf=function(a,b){var c=a.m.ph;return/^[\s\xa0]*$/.test(null==b?"":String(b))||/^[\s\xa0]*$/.test(null==c?"":String(c))||b==a.m.ph};Zf.prototype.f=function(){this.close();this.Ka=this.R=null;delete V[this.name];J(this.ec);delete this.ec;Zf.H.f.call(this)};
var Yf=function(){for(var a in V)J(V[a])};var cg=function(a,b,c,d,e){a=new R(a);0!=b&&(S(a),a.C.set("authuser",b));null!=c&&(S(a),a.C.set("pageId",c));null!=d&&(S(a),a.C.set("service",d));this.Fd=a.toString();this.xa=e;this.yd=0};cg.prototype.start=function(){};cg.prototype.send=function(a,b,c){var d=new R(this.Fd);for(g in c){var e=g,f=c[g];S(d);d.C.set(e,f)}c=d.toString();d=x(this.Kc,this,this.yd++);var g=new T;Ge.push(g);d&&g.Xa("complete",d);g.Yb("ready",g.ld);g.qc=!0;g.send(c,"POST",a,b)};
cg.prototype.Kc=function(a,b){b=b.target;Oe(b)?this.xa.ua.send("ss",[a]):(b=Qe(b),this.xa.ua.send("sf",[a,b]))};var dg=function(a,b,c,d,e){this.td=new cg(a,b,c,d,this);a=new R(e||window.location.href);this.Kd=JSON.parse(a.C.get("xpc")||"");this.ua=null};dg.prototype.Vb=function(){this.ua=new Zf(this.Kd);var a=x(dg.prototype.send,this);this.ua.lc.s={M:a,Qc:!0};this.ua.connect()};dg.prototype.send=function(a){this.td.send(a[0],a[1],a[2])};dg.prototype.Kc=function(a,b){b=b.target;Oe(b)?this.ua.send("ss",[a]):this.ua.send("sf",[a,Qe(b)])};dg.prototype.init=dg.prototype.Vb;ia("invalidation.XpcSenderServer",dg,void 0);
